
services:
  - type: web
    name: uni-finder-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: DATA_JSON_PATH
        value: data/programs.json
      - key: DATA_REFRESH_TTL_SECONDS
        value: "21600"
