
services:
  - type: web
    name: uni-finder-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: GOOGLE_CSE_KEY
        sync: false
      - key: GOOGLE_CSE_CX
        sync: false
      - key: SEARCH_CACHE_TTL_SECONDS
        value: "21600"
