services:
  - type: web
    name: uni-finder-bot
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: GITHUB_DATA_REPO
        sync: false
      - key: GITHUB_DATA_PATH
        sync: false
      - key: GITHUB_DATA_BRANCH
        sync: false
      - key: DATA_REFRESH_TTL_SECONDS
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: ADMIN_USER_ID
        sync: false
