name: Build dataset

on:
  workflow_dispatch: {}
  schedule:
    - cron: "27 3 * * *"
  push:
    paths:
      - "scraper_latest/**"
      - ".github/workflows/update-data.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install scraper requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper_latest/requirements.txt

      - name: Build dataset
        run: |
          python scraper_latest/build_dataset.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/latest.csv public/data/latest.json || true
          if git diff --staged --quiet; then
            echo "No dataset changes."
          else
            git commit -m "data: update latest dataset [skip ci]"
            git push
          fi
